# Generated by Django 3.1.7 on 2021-05-06 06:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=10, verbose_name='类型')),
                ('object_id', models.PositiveIntegerField(db_index=True, null=True, verbose_name='对象Id')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='用户Id')),
                ('from_user_id', models.IntegerField(blank=True, null=True, verbose_name='发送用户Id')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否读取')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='详情')),
            ],
            options={
                'verbose_name': 'UserMessage',
                'verbose_name_plural': 'UserMessage',
            },
        ),
    ]
